# Generated by Django 4.2.2 on 2023-06-12 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LGA',
            fields=[
                ('uniqueid', models.AutoField(primary_key=True, serialize=False)),
                ('lga_id', models.IntegerField()),
                ('lga_name', models.CharField(max_length=50)),
                ('lga_description', models.TextField()),
                ('entered_by_user', models.CharField(max_length=50)),
                ('date_entered', models.DateTimeField()),
                ('user_ip_address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('party_id', models.CharField(max_length=11)),
                ('party_name', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', models.IntegerField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('uniqueid', models.AutoField(primary_key=True, serialize=False)),
                ('ward_id', models.IntegerField()),
                ('ward_name', models.CharField(max_length=50)),
                ('ward_description', models.TextField()),
                ('entered_by_user', models.CharField(max_length=50)),
                ('date_entered', models.DateTimeField()),
                ('user_ip_address', models.CharField(max_length=50)),
                ('lga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polling_units.lga')),
            ],
        ),
        migrations.CreateModel(
            name='PollingUnit',
            fields=[
                ('uniqueid', models.AutoField(primary_key=True, serialize=False)),
                ('polling_unit_id', models.IntegerField()),
                ('unique_ward_id', models.IntegerField(null=True)),
                ('polling_unit_number', models.CharField(max_length=50, null=True)),
                ('polling_unit_name', models.CharField(max_length=50, null=True)),
                ('polling_unit_description', models.TextField(null=True)),
                ('lat', models.CharField(max_length=255, null=True)),
                ('long', models.CharField(max_length=255, null=True)),
                ('entered_by_user', models.CharField(max_length=50, null=True)),
                ('date_entered', models.DateTimeField(null=True)),
                ('user_ip_address', models.CharField(max_length=50, null=True)),
                ('lga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polling_units.lga')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polling_units.state')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polling_units.ward')),
            ],
        ),
        migrations.AddField(
            model_name='lga',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polling_units.state'),
        ),
    ]
