# Generated by Django 4.2.2 on 2023-06-13 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polling_units', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lga',
            name='date_entered',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='lga',
            name='lga_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lga',
            name='user_ip_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pollingunit',
            name='date_entered',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pollingunit',
            name='entered_by_user',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pollingunit',
            name='lat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pollingunit',
            name='long',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pollingunit',
            name='polling_unit_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pollingunit',
            name='polling_unit_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pollingunit',
            name='polling_unit_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pollingunit',
            name='unique_ward_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pollingunit',
            name='user_ip_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ward',
            name='date_entered',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='ward',
            name='user_ip_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ward',
            name='ward_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PartyResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('result', models.CharField(blank=True, max_length=255, null=True)),
                ('date_entered', models.DateTimeField(blank=True, null=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polling_units.party')),
                ('polling_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polling_units.pollingunit')),
            ],
        ),
    ]
